sudo: false
language: ruby
rvm:
  - 2.1.5
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install: gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
# this should not be necessary, since the gemspec defines the Rakefile as an extension, which triggers this by default
#  - rake jarfile_lock 
script: rake test
