---
- include: vagrant/ansible/site.yml

- hosts: [rvm]
  roles:
  - role: rvm_io.rvm1-ruby
    become: yes
    when: rvm1_rubies|length > 0

- hosts: [all]
  tasks:
  - name: install gem bundler
    command: /bin/bash -lc "rvm all do gem install bundler"
    args:
      chdir: "/project"
  - name: bundle install
    command: /bin/bash -lc "rvm all do bundle install"
    args:
      chdir: "/project" 
  - name: gem install ruby-debug-ide
    command: /bin/bash -lc "rvm all do gem install ruby-debug-ide"
    args:
      chdir: "/project"
